# Generated by Django 5.0.1 on 2024-02-12 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultaion_fees',
            field=models.DecimalField(decimal_places=3, default=300, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_slots',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='A+', max_length=5),
        ),
    ]
