# Generated by Django 5.0.1 on 2024-02-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_patient_user_otpmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='aadhar_card_number',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='license_file',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='license_number',
        ),
    ]
