# Generated by Django 5.0.1 on 2024-02-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_doctor_hospital_doctor_about_me_doctor_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='consultation_slots',
        ),
    ]
