# Generated by Django 5.0.1 on 2024-02-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_doctor_consultation_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation_slots',
            field=models.IntegerField(default=5),
        ),
    ]
