# Generated by Django 5.0.1 on 2024-02-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_doctor_consultation_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.IntegerField(default=4),
        ),
    ]
