# Generated by Django 5.0.1 on 2024-02-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_doctor_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_time',
            field=models.TextField(default='10AM to 5PM', max_length=50),
        ),
    ]
