# Generated by Django 5.0.1 on 2024-02-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_doctor_consultation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='college_name',
            field=models.TextField(default='Not Available', max_length=50),
        ),
    ]
