# Generated by Django 5.0.1 on 2024-02-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_doctoravailability_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='doctor_availability',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='patient',
        ),
        migrations.AddField(
            model_name='transaction',
            name='doctor_id',
            field=models.CharField(default=1, max_length=200, verbose_name='Doctor ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='patient_id',
            field=models.CharField(default=1, max_length=200, verbose_name='Patient ID'),
            preserve_default=False,
        ),
    ]
