# Generated by Django 5.0.1 on 2024-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_transaction_doctor_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='COMPLETED', max_length=20),
        ),
    ]
